package org.androidtown.mypaintlib;

/**
 * Created by ejchoi on 2017-03-13.
 */

public class PaintBrushDefine {
    public static final int PAINT_BRUSH_MAX_RADIUS = 30;
    public static final int PAINT_BRUSH_MAX_TILE_SIZE = ((PAINT_BRUSH_MAX_RADIUS+2) * 2);   // 64

    public static final int PAINT_BRUSH_R = 128;
    public static final int PAINT_BRUSH_G = 128;
    public static final int PAINT_BRUSH_B = 128;

    public enum PaintBrushType {
        PAINT_BRUSH_NONE(0),
        PAINT_BRUSH_DEFAULT(1),
        PAINT_BRUSH_CHARCOAL(2),
        PAINT_BRUSH_SHORT_GRASS(3),
        PAINT_BRUSH_WATERCOLOR_EXPRESSIVE(4),
        PAINT_BRUSH_LEAVES(5),
        PAINT_BRUSH_CALLIGRAPHY(6),
        PAINT_BRUSH_GLOW(7);

        private PaintBrushType(int nativeInt) {
            this.nativeInt = nativeInt;
        }
        final int nativeInt;
    }

    public enum PaintBrushInput {
        PAINT_BRUSH_INPUT_PRESSURE(0),
        PAINT_BRUSH_INPUT_SPEED1(1),
        PAINT_BRUSH_INPUT_SPEED2(2),
        PAINT_BRUSH_INPUT_RANDOM(3),
        PAINT_BRUSH_INPUT_STROKE(4),
        PAINT_BRUSH_INPUT_DIRECTION(5),
        PAINT_BRUSH_INPUT_TILT_DECLINATION(6),
        PAINT_BRUSH_INPUT_TILT_ASCENSION(7),
        PAINT_BRUSH_INPUT_CUSTOM(8),
        PAINT_BRUSH_INPUTS_COUNT(9);

        private PaintBrushInput(int nativeInt) {
            this.nativeInt = nativeInt;
        }
        final int nativeInt;
    }

    public enum PaintBrushSetting {
        PAINT_BRUSH_SETTING_OPAQUE(0),
        PAINT_BRUSH_SETTING_OPAQUE_MULTIPLY(1),
        PAINT_BRUSH_SETTING_OPAQUE_LINEARIZE(2),
        PAINT_BRUSH_SETTING_RADIUS_LOGARITHMIC(3),
        PAINT_BRUSH_SETTING_HARDNESS(4),
        PAINT_BRUSH_SETTING_ANTI_ALIASING(5),
        PAINT_BRUSH_SETTING_DABS_PER_BASIC_RADIUS(6),
        PAINT_BRUSH_SETTING_DABS_PER_ACTUAL_RADIUS(7),
        PAINT_BRUSH_SETTING_DABS_PER_SECOND(8),
        PAINT_BRUSH_SETTING_RADIUS_BY_RANDOM(9),
        PAINT_BRUSH_SETTING_SPEED1_SLOWNESS(10),
        PAINT_BRUSH_SETTING_SPEED2_SLOWNESS(11),
        PAINT_BRUSH_SETTING_SPEED1_GAMMA(12),
        PAINT_BRUSH_SETTING_SPEED2_GAMMA(13),
        PAINT_BRUSH_SETTING_OFFSET_BY_RANDOM(14),
        PAINT_BRUSH_SETTING_OFFSET_BY_SPEED(15),
        PAINT_BRUSH_SETTING_OFFSET_BY_SPEED_SLOWNESS(16),
        PAINT_BRUSH_SETTING_SLOW_TRACKING(17),
        PAINT_BRUSH_SETTING_SLOW_TRACKING_PER_DAB(18),
        PAINT_BRUSH_SETTING_TRACKING_NOISE(19),
        PAINT_BRUSH_SETTING_COLOR_H(20),
        PAINT_BRUSH_SETTING_COLOR_S(21),
        PAINT_BRUSH_SETTING_COLOR_V(22),
        PAINT_BRUSH_SETTING_RESTORE_COLOR(23),
        PAINT_BRUSH_SETTING_CHANGE_COLOR_H(24),
        PAINT_BRUSH_SETTING_CHANGE_COLOR_L(25),
        PAINT_BRUSH_SETTING_CHANGE_COLOR_HSL_S(26),
        PAINT_BRUSH_SETTING_CHANGE_COLOR_V(27),
        PAINT_BRUSH_SETTING_CHANGE_COLOR_HSV_S(28),
        PAINT_BRUSH_SETTING_SMUDGE(29),
        PAINT_BRUSH_SETTING_SMUDGE_LENGTH(30),
        PAINT_BRUSH_SETTING_SMUDGE_RADIUS_LOG(31),
        PAINT_BRUSH_SETTING_ERASER(32),
        PAINT_BRUSH_SETTING_STROKE_THRESHOLD(33),
        PAINT_BRUSH_SETTING_STROKE_DURATION_LOGARITHMIC(34),
        PAINT_BRUSH_SETTING_STROKE_HOLDTIME(35),
        PAINT_BRUSH_SETTING_CUSTOM_INPUT(36),
        PAINT_BRUSH_SETTING_CUSTOM_INPUT_SLOWNESS(37),
        PAINT_BRUSH_SETTING_ELLIPTICAL_DAB_RATIO(38),
        PAINT_BRUSH_SETTING_ELLIPTICAL_DAB_ANGLE(39),
        PAINT_BRUSH_SETTING_DIRECTION_FILTER(40),
        PAINT_BRUSH_SETTING_LOCK_ALPHA(41),
        PAINT_BRUSH_SETTING_COLORIZE(42),
        PAINT_BRUSH_SETTING_SNAP_TO_PIXEL(43),
        PAINT_BRUSH_SETTING_PRESSURE_GAIN_LOG(44),
        PAINT_BRUSH_SETTINGS_COUNT(45);

        private PaintBrushSetting(int nativeInt) {
            this.nativeInt = nativeInt;
        }
        final int nativeInt;
    }

    public enum PaintBrushState {
        PAINT_BRUSH_STATE_X(0),
        PAINT_BRUSH_STATE_Y(1),
        PAINT_BRUSH_STATE_PRESSURE(2),
        PAINT_BRUSH_STATE_DIST(3),
        PAINT_BRUSH_STATE_ACTUAL_RADIUS(4),
        PAINT_BRUSH_STATE_SMUDGE_RA(5),
        PAINT_BRUSH_STATE_SMUDGE_GA(6),
        PAINT_BRUSH_STATE_SMUDGE_BA(7),
        PAINT_BRUSH_STATE_SMUDGE_A(8),
        PAINT_BRUSH_STATE_LAST_GETCOLOR_R(9),
        PAINT_BRUSH_STATE_LAST_GETCOLOR_G(10),
        PAINT_BRUSH_STATE_LAST_GETCOLOR_B(11),
        PAINT_BRUSH_STATE_LAST_GETCOLOR_A(12),
        PAINT_BRUSH_STATE_LAST_GETCOLOR_RECENTNESS(13),
        PAINT_BRUSH_STATE_ACTUAL_X(14),
        PAINT_BRUSH_STATE_ACTUAL_Y(15),
        PAINT_BRUSH_STATE_NORM_DX_SLOW(16),
        PAINT_BRUSH_STATE_NORM_DY_SLOW(17),
        PAINT_BRUSH_STATE_NORM_SPEED1_SLOW(18),
        PAINT_BRUSH_STATE_NORM_SPEED2_SLOW(19),
        PAINT_BRUSH_STATE_STROKE(20),
        PAINT_BRUSH_STATE_STROKE_STARTED(21),
        PAINT_BRUSH_STATE_CUSTOM_INPUT(22),
        PAINT_BRUSH_STATE_RNG_SEED(23),
        PAINT_BRUSH_STATE_ACTUAL_ELLIPTICAL_DAB_RATIO(24),
        PAINT_BRUSH_STATE_ACTUAL_ELLIPTICAL_DAB_ANGLE(25),
        PAINT_BRUSH_STATE_DIRECTION_DX(26),
        PAINT_BRUSH_STATE_DIRECTION_DY(27),
        PAINT_BRUSH_STATE_DECLINATION(28),
        PAINT_BRUSH_STATE_ASCENSION(29),
        PAINT_BRUSH_STATES_COUNT(30);

        private PaintBrushState(int nativeInt) {
            this.nativeInt = nativeInt;
        }
        final int nativeInt;
    }

    public static final int PAINT_BRUSH_RNG_QUALITY = 19;
    public static final int PAINT_BRUSH_RNG_TT = 7;
    public static final int PAINT_BRUSH_RNG_KK = 10;
    public static final int PAINT_BRUSH_RNG_LL = 7;

    public static final int PAINT_BRUSH_CPOINTS_COUNT = 8;

    public static final int PAINT_BRUSH_CALC_COUNT = 2;
}
